Everything/Controllers/CarritoController.cs
using Everything.Models.Business;
using Everything.Models.Entities;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Everything.Controllers
{
    public class CarritoController : Controller
    {

        ProductoBusiness productoBusiness = new ProductoBusiness();
        OrdenBusiness ordenBusiness = new OrdenBusiness();
        OrdenDetalleBusiness ordenDetalleBusiness = new OrdenDetalleBusiness();

        // GET: Carrito
        public ActionResult Index()
        {
            List<orden_detalle> carrito = (List<orden_detalle>)Session["carrito"];
            return View(carrito);
        }

        public ActionResult agregar(int id)
        {
            producto producto = productoBusiness.findById(id);
            orden_detalle item = new orden_detalle();

            item.producto = producto.id;
            item.detalle = producto.nombre;
            item.precio = producto.precio;
            item.cantidad = 1;
            item.total = item.cantidad * item.precio;

            ViewBag.producto = producto;

            return View(item);
        }

        [HttpPost]
        public ActionResult agregar(orden_detalle item)
        {
            if (ModelState.IsValid)
            {
                List<orden_detalle> carrito = (List<orden_detalle>)Session["carrito"];
                carrito.Add(item);

                Session["carrito"] = carrito;

                return RedirectToAction("index", "Home", null);
            }
            else
            {
                return RedirectToAction("add");
            }
        }

        public ActionResult editar(int id)
        {
            List<orden_detalle> carrito = (List<orden_detalle>)Session["carrito"];

            return View(carrito[id]);
        }

        [HttpPost]
        public ActionResult editar(int id, orden_detalle item)
        {
            List<orden_detalle> carrito = (List<orden_detalle>)Session["carrito"];
            carrito[id] = item;

            Session["carrito"] = carrito;

            return RedirectToAction("index");
        }

        public ActionResult finalizar()
        {
            usuario usuario = (usuario)Session["usuario"];
            List<orden_detalle> carrito = (List<orden_detalle>)Session["carrito"];

            if (usuario == null)
            {
                return RedirectToAction("login", "Account");
            }
            else if (carrito.Count > 0)
            {
                decimal total = 0;
                foreach (orden_detalle item in carrito)
                {
                    total += item.total;
                }

                orden orden = new orden();
                orden.orden_fecha = DateTime.Now.ToString("yyyy-MM-dd");
                orden.delivery_fecha = DateTime.Now.AddDays(4).ToString("yyyy-MM-dd");
                orden.tipo_documento = "BOLETA";
                orden.usuario = usuario.id;
                orden.total = total;

                ordenBusiness.create(orden);

                string productos = "";
                foreach (orden_detalle item in carrito)
                {
                    item.orden = orden.id;
                    ordenDetalleBusiness.create(item);
                    productos += item.detalle + " | " + item.cantidad + " |  s/." + item.precio + " | s/." + item.total + "\n";
                }

                productos += "TOTAL PAGAR: s/." + orden.total;

                OrdenBusiness.enviarCorreo(usuario.correo, productos);

                ViewBag.correo = usuario.correo;
                Session["carrito"] = new List<orden_detalle>();
            }

            return View();
        }

    }
}

Everything/Views/Carrito/Index.cshtml
@model IEnumerable<Everything.Models.Entities.orden_detalle>

@{
    ViewBag.Title = "Index";
}


<script type="text/javascript">
    $(document).ready(function () {
        $('.btnEditar').click(function (e) {
            $('.modal-title').text('Actualizar cantidad');
            $('.modal-body').load("/Carrito/editar/" + $(this).attr("data-id"));
        });
    });
</script>

<div id="modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                @*contenido del modal*@
            </div>
        </div>
    </div>
</div>

<h2>Mi carrito</h2>

<div style="float:left; margin: 10px 0"><a href="@Url.Action("index","Home")" class="btn btn-default">Agregar</a></div>
<div style="float:right; margin: 10px 0"><a href="@Url.Action("finalizar","Carrito")" class="btn btn-success">Finalizar</a></div>

<table class="table">
    <tr>
        <th>
            item
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.detalle)*@
            producto
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.total)
        </th>
        <th></th>
    </tr>

    @{ int i = 1; }
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div>@(i++)</div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.detalle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            <td>
                <a href="#modal" class="btnEditar" data-toggle="modal" data-id="@(i -2)">Editar</a>
            </td>
        </tr>
    }

</table>

Everything/Views/Carrito/agregar.cshtml
@model Everything.Models.Entities.orden_detalle

@{
    Layout = null;
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#cantidad').change(function (e) {
            var precio = $('#precio').val();
            var cantidad = $('#cantidad').val();
            $('#hidden_total').val(precio * cantidad);
            $('#total').val(precio * cantidad);
            console.log('Se actualizo el total');
        });
    });
</script>


<p style="font-size: 20px; margin-bottom: 10px ;overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: center; text-transform:uppercase">@ViewBag.producto.nombre</p>
<img style="width: 100%; height:auto" src="@Url.Content("~/Imagenes/" + @ViewBag.producto.imagen)" />
<p style="margin-top: 10px; text-align: justify;">@ViewBag.producto.descripcion</p>

<hr/>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.orden)
        @Html.HiddenFor(model => model.producto)
        @Html.HiddenFor(model => model.detalle)
        @Html.HiddenFor(model => model.precio)
        @Html.HiddenFor(model => model.total, new { Id = "hidden_total"})

        <div class="form-group">
            <label class="control-label col-md-2" for="precio">precio</label>
            <div class="col-md-10">
                <input class="form-control" value="@ViewBag.producto.precio" disabled="disabled">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger cboCantidad" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Everything/Views/Carrito/editar.cshtml
@model Everything.Models.Entities.orden_detalle

@{
    Layout = null;
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#cantidad').change(function (e) {
            var precio = $('#precio').val();
            var cantidad = $('#cantidad').val();
            $('#hidden_total').val(precio * cantidad);
            $('#total').val(precio * cantidad);
            console.log('Se actualizo el total');
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.orden)
        @Html.HiddenFor(model => model.producto)
        @Html.HiddenFor(model => model.detalle)
        @Html.HiddenFor(model => model.precio)
        @Html.HiddenFor(model => model.total, new { Id = "hidden_total" })

        <div class="form-group">
            @Html.LabelFor(model => model.detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detalle, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Everything/Views/Carrito/finalizar.cshtml
@{
    ViewBag.Title = "finalizar";
}

<div style="width:50%; margin: auto;text-align:center; margin-top: 50px">
    <h2>Orden de compra generada</h2>
    <img src="~/Imagenes/shop_success.png" />
    <p>En unos minutos nos estamos comunicando con usted. Además, hemos enviado un correo a @ViewBag.correo con el detalle de la orden.</p>
</div>